defaults: &defaults
  # andrologie: { '16' =>  %w(不限 B超引导下前列腺活检术 前列腺针吸细胞学活检术 前列腺按摩 前列腺注射 前列腺特殊治疗(微波法) 前列腺特殊治疗(射频法) 前列腺特殊治疗(激光法)), '22' =>  %w(不限 阴茎延长 阴茎增粗), '23' =>  %w(不限 包皮环切术 激光手术), '20' =>  %w(不限 精索静脉转流术 精索静脉转流术 精索静脉曲张栓塞术 精索静脉曲张高位结扎术 精索静脉曲张分流术), '19' =>  %w(不限 阴囊、双侧睾丸、附睾B超检查 阴囊、双侧睾丸、附睾彩色多普勒超声检查 睾丸阴茎海绵体活检术(包括穿刺、切开) 睾丸鞘膜翻转术 睾丸附件扭转探查术(含睾丸扭转复位术) 睾丸破裂修补术 睾丸固定术(含疝囊高位结扎术) 睾丸切除术 睾丸肿瘤腹膜后淋巴结清扫术 自体睾丸移植术 附睾睾丸活检术), '18' =>  %w(不限 阴茎海绵体造影 夜间阴茎胀大试验(含硬度计法) 阴茎超声血流图检查 阴茎勃起神经检查(含肌电图检查) 睾丸阴茎海绵体活检术(包括穿刺、切开) 阴茎海绵体内药物注射 阴茎赘生物电灼术(包括冷冻术) 阴茎动脉测压术 阴茎海绵体灌流治疗术 尿道下裂阴茎下弯矫治术 阴茎包皮过短整形术  阴茎外伤清创术 阴茎再植术 阴茎囊肿切除术 阴茎硬节切除术 阴茎部分切除术(包括阴茎癌切除术) 阴茎全切术(阴茎癌切除术) 阴茎重建成形术(含假体置放术) 阴茎再造术(含龟头再造和假体置放) 阴茎畸型整形术(包括阴茎弯曲矫正) 阴茎延长术(包括阴茎加粗、隐匿型延长术) 阴茎阴囊移位整形术(增加会阴型尿道下裂修补时加收50%) 尿道阴茎海绵体分流术 阴茎血管重建术 阴茎海绵体分离术 阴茎静脉结扎术(包括海绵体静脉、背深静脉)), '21' =>  %w(不限 高位隐睾下降固定术(含疝修补术)经腹腔镜隐睾探查术(含隐睾切除术)}
  # andrologie: "test"
  andrology: 
    0:
      - 不限 
      - (含淋巴结清扫和取活检) 
      - 耻骨上前列腺切除术 
      - 耻骨后前列腺切除术
      - 经会阴前列腺切除术 
      - 前列腺囊肿切除术 
      - 前列腺脓肿切开术
      - 经尿道前列腺电切术(激光法)
      - 经尿道前列腺电切术(电切法)
      - 经尿道前列腺电切术(汽化法) 
      - 经尿道前列腺气囊扩张术
      - 经尿道前列腺支架置入术
      - 前列腺摘除术
    16:
      - 不限 
      - B超引导下前列腺活检术 
      - 前列腺针吸细胞学活检术
      - 前列腺按摩 
      - 前列腺注射 
      - 前列腺特殊治疗(微波法) 
      - 前列腺特殊治疗(射频法)
      - 前列腺特殊治疗(激光法)
    22:
      - 不限 
      - 阴茎延长 
      - 阴茎增粗
    23:
      - 不限 
      - 包皮环切术 
      - 激光手术
    20:
      - 不限 
      - 精索静脉转流术 
      - 精索静脉转流术 
      - 精索静脉曲张栓塞术 
      - 精索静脉曲张高位结扎术 
      - 精索静脉曲张分流术
    19:
      - 不限 
      - 阴囊、双侧睾丸、附睾B超检查 阴囊、双侧睾丸、附睾彩色多普勒超声检查 
      - 睾丸阴茎海绵体活检术(包括穿刺、切开)
      - 睾丸鞘膜翻转术
      - 睾丸附件扭转探查术(含睾丸扭转复位术)
      - 睾丸破裂修补术 
      - 睾丸固定术(含疝囊高位结扎术) 
      - 睾丸切除术 
      - 睾丸肿瘤腹膜后淋巴结清扫术
      - 自体睾丸移植术
      - 附睾睾丸活检术 
    18:
      - 不限 
      - 阴茎海绵体造影
      - 夜间阴茎胀大试验(含硬度计法)
      - 阴茎超声血流图检查
      - 阴茎勃起神经检查(含肌电图检查) 
      - 睾丸阴茎海绵体活检术(包括穿刺、切开) 
      - 阴茎海绵体内药物注射 
      - 阴茎赘生物电灼术(包括冷冻术) 
      - 阴茎动脉测压术 
      - 阴茎海绵体灌流治疗术 
      - 尿道下裂阴茎下弯矫治术 
      - 阴茎包皮过短整形术  
      - 阴茎外伤清创术 
      - 阴茎再植术 
      - 阴茎囊肿切除术 
      - 阴茎硬节切除术 
      - 阴茎部分切除术(包括阴茎癌切除术) 
      - 阴茎全切术(阴茎癌切除术) 
      - 阴茎重建成形术(含假体置放术) 
      - 阴茎再造术(含龟头再造和假体置放) 
      - 阴茎畸型整形术(包括阴茎弯曲矫正) 
      - 阴茎延长术(包括阴茎加粗、隐匿型延长术) 
      - 阴茎阴囊移位整形术(增加会阴型尿道下裂修补时加收50%) 
      - 尿道阴茎海绵体分流术 
      - 阴茎血管重建术 
      - 阴茎海绵体分离术 
      - 阴茎静脉结扎术(包括海绵体静脉、背深静脉)
    21:
      - 不限 
      - 高位隐睾下降固定术（含疝修补术） 
      - 经腹腔镜隐睾探查术（含隐睾切除术）
  plastic:
    0: 
      - 不限 
      - 双眼皮（埋线法） 
      - 双眼皮（切开法） 
      - 内眼角 
      - 外眼角 
      - 上眼皮下垂
      - 上下眼睑
      - 眼睫毛皮肤切除
      - 眼睫毛植毛
      - 祛眼袋
      - 内眦成形术

    1:
      - 不限 
      - 凹陷性疤痕
      - 面颈疤痕修复
      - 体表疤痕修复
      - 体表肿物切除
      - 植皮修复术
    59:
      - 不限 
      - 隆鼻术
      - 鼻再造
      - 体表疤痕修复
      - 体表肿物切除
      - 植皮修复术
      - 鼻翼缩小
      - 鼻头缩小
      - 鼻翼再造
      - 鼻小柱再造
      - 朝天鼻矫正
      - 鼻尖整形
    3:
      - 不限 
      - 全耳再造修复
      - 外耳再造修复
      - 小耳畸形
      - 招风耳矫正
    4:
      - 不限 
      - 肉毒素除皱术
      - 小切口除皱
      - 额部除皱
      - 面部悬吊术
      - 隆頦术
      - 顳部填充术
      - 颧骨矫形
      - 下颌角矫形
      - 颚裂修复术
      - 酒窝成形
      - 注射瘦脸
      - 丰太阳穴
      - 注射丰下巴
      - 丰额头
    5:
      - 不限 
      - 光子嫩肤
      - 激光美容
      - 激光除皱
      - 面部嫩肤
      - 电波拉皮
  tcm:
    0:
      - 不限 
      - 颈椎病推拿治疗
      - 寰枢关节失稳推拿治疗
      - 颈椎小关节紊乱推拿治疗
      - 胸椎小关节紊乱推拿治疗
      - 腰椎小关节紊乱推拿治疗
      - 腰椎间盘突出推拿治疗
      - 第三腰椎横突综合征推拿治疗
      - 骶髂关节紊乱症推拿治疗
      - 强直性脊柱炎推拿治疗
      - 外伤性截瘫推拿治疗
      - 退行性脊柱炎推拿治疗
    72:
      - 不限
      - 灸法(艾柱灸)
      - 灸法(艾条灸)
      - 灸法(艾箱灸)
      - 灸法(天灸)
      - 灸法(其他灸)
      - 隔物灸法(隔姜灸)
      - 隔物灸法(药饼灸)
      - 隔物灸法(隔盐灸)
      - 隔物灸法(其它灸)
      - 灯火灸
      - 药线点灸
      - 拔罐疗法(火罐)（3罐/次）
      - 拔罐疗法(电火罐)（3罐/次）
      - 拔罐疗法(闪罐)（3罐/次）
      - 拔罐疗法(着罐)（3罐/次）
      - 拔罐疗法(电罐)（3罐/次）
      - 拔罐疗法(磁疗罐)（3罐/次）
      - 拔罐疗法(真空拔罐)（3罐/次）
      - 拔罐疗法(其它罐)（3罐/次）
      - 药物罐 
      - 水罐
      - 督灸
      - 大灸
      - 雷火灸
      - 太乙神针灸
    1000:
      - 不限
      - 落枕推拿治疗
      - 颈椎病推拿治疗
      - 颈椎病正骨复位
      - 肩周疾病推拿治疗
      - 网球肘推拿治疗
      - 急性腰扭伤推拿治疗
      - 腰部疾病推拿治疗
      - 腰椎间盘突出正骨复位
      - 膝关节骨性关节炎推拿治疗
      - 内科慢性腹泻推拿治疗
      - II型糖尿病推拿治疗
      - 内科便秘推拿治疗
      - 慢性胃病推拿治疗
      - 内科失眠推拿治疗
      - 胃下垂推拿治疗
      - 月经不调推拿治疗
      - 痛经推拿治疗
      - 其他推拿治疗
      - 小儿捏脊治疗
      - 药棒穴位按摩治疗（3穴位）
      - 脊柱小关节紊乱推拿治疗
      - 小儿斜颈推拿治疗
      - 环枢关节半脱位推拿治疗
    73:
      - 不限
      - 普通针刺（体针）（5穴位/次）
      - 普通针刺(快速针)（5穴位/次）
      - 普通针刺(磁针)（5穴位/次）
      - 普通针刺(金针)（5穴位/次）
      - 普通针刺(姜针)（5穴位/次）
      - 普通针刺(药针)（5穴位/次）
      - 其它普通针刺（5穴位/次）
      - 温针（5穴位/次）
      - 手指点穴（5穴位/次）
      - 馋针
      - 微针针刺
      - 锋钩针
      - 头皮针
      - 眼针（单眼）
      - 梅花针
      - 七星针
      - 火针(3穴位)
      - 电火针(3穴位)
      - 埋针治疗
      - 耳针(单耳)
      - 芒针
      - 电针(普通电针)（2穴位）
      - 浮针
      - 微波针（2穴位）
      - 激光针（2穴位）
      - 磁热疗法（2穴位）
      - 放血疗法
      - 穴位注射
      - 穴位封闭
      - 自血疗法
      - 穴位贴敷治疗
      - 内脏平滑肌痉挛性疼痛止痛敷贴
      - 杵针
      - 圆针
    74:
      - 不限
      - 直肠脱出复位治疗
      - 三度直肠脱垂复位治疗
      - 直肠周围硬化剂注射治疗
      - 内痔硬化剂注射治疗(枯痔治疗)
      - 高位复杂肛瘘挂线治疗
      - 血栓性外痔切除术
      - 环状混合痔切除术
      - 环状混合痔脱出嵌顿切除术
      - 混合痔外剥内扎术
      - 肛外括约肌折叠术
      - 直肠前突修补术
      - 肛瘘封堵术
      - 肛周药物注射封闭术
      - 肛周坏死性筋膜炎清创术
      - 肛门直肠周围脓腔搔刮术
      - 直肠前突出注射术
      - 直肠脱垂注射术
    75:
      - 不限
      - 骨折橇拨复位术
      - 骨折经皮钳夹复位术
      - 骨折闭合复位经皮穿刺（钉）内固定术
      - 骨折闭合复位经皮穿刺（钉）内固定术四肢长骨干、近关节加收
      - 关节脱位手法整复术
      - 陈旧性脱位关节脱位手法整复术
      - 髋关节脱位手法整复术
      - 下颌关节脱位手法整复术
      - 指(趾)间关节脱位手法整复术
      - 骨折外固定架固定术
      - 骨折外固定架固定术复查调整
      - 骨折夹板外固定
      - 骨折夹板外固定复查调整
      - 关节错缝术
      - 麻醉下腰椎间盘突出症大手法治疗
      - 关节粘连传统松解术
      - 中医定向透药疗法
      - 腱鞘囊肿挤压术
      - 腱鞘囊肿挤压术
      - 腰间盘三维牵引复位术
    76:
      - 不限
      - 白内障针拨术（单眼）
      - 白内障针拨术（双眼）
      - 白内障针拨吸出术（单眼）
      - 白内障针拨吸出术（双眼）
      - 白内障针拨吸出术（双眼）
      - 白内障针拨套出术（双眼）
      - 眼结膜囊穴位注射（单眼）
      - 眼结膜囊穴位注射（双眼）
      - 小针刀治疗
      - 钩针疗法
      - 刃针治疗
      - 红皮病清消术
      - 扁桃体烙法治疗
      - 鼻中隔烙法治疗
      - 药线引流治疗
      - 耳咽中药吹粉治疗
      - 中药硬膏热贴敷治疗
      - 中药直肠滴入治疗
      - 刮痧治疗
      - 烫熨治疗
      - 体表瘘管切开搔爬术
      - 足底反射治疗
    77:
      - 不限
      - 中药化腐清创术
      - 中药涂擦治疗（>10%体表面积）
      - 中药热奄包治疗
      - 中药封包治疗
      - 中药熏洗治疗
      - 中药熏洗治疗（半身）
      - 中药熏洗治疗（全身）
      - 中药蒸汽浴治疗(30分钟)
      - 中药蒸汽浴治疗（>30分钟）
      - 中药塌渍治疗（10%体表面积）
      - 中药塌渍治疗（>10%体表面积）
      - 中药熏药治疗
      - 赘生物中药腐蚀治疗（每赘生物）
      - 挑治
      - 割治
  gynaecology:
    0:
      - 不限 
      - 剖腹产
      - 卵巢囊切除术
      - 子宫全切
      - 子宫次全切
      - 取环
      - 放环
      - 清宫
      - 无痛清宫
      - 引产术
      - 子宫肌瘤剜除
    83:
      - 不限
      - 阴道分泌物检查
      - 细菌性阴道病监测（BV）
    84:
      - 不限
      - 尿妊娠试验
      - 尿HL检测
      - 尿十一项+尿沉渣
      - 尿微量白蛋白
    85:
      - 不限
      - 单纯疱疹病毒抗体测定四项
      - 淋球菌培养
      - 衣原体抗原
      - 支原体培养及药敏
      - 宫颈刮片细胞学检查
      - 标本病例检查
      - 弓形体抗原测定
      - 梅毒快速血浆反应实验（TRUST）
      - 梅毒螺旋体异性抗体（TPPA）
      - TCT脱落细胞检查
    87:
      - 不限
      - 电子数码阴道镜检查
      - 妇科常规检查
    82:
      - 不限
      - 阴道彩超
      - 阴道黑白超
      - 腹部彩色超声检查
      - 子宫附件B超
      - 孕检彩色超声检查
    86:
      - 不限
      - 全血细胞分析
      - ABO血型定型
      - Rb(D)定型
      - 凝血四项（PT，TT，APTT，FIB）
      - 乙肝表面抗原
      - 术前四项（乙肝两对半、RPR、抗HCV、抗HIV）
      - 不孕五项（化学发光法）优生五项（化学发光法）
      - 性激素六项
      - 血清泌乳素测定
      - 血清促黄体生成素测定
      - 血清促卵泡刺激素测定
      - 血清绒毛促性激素定量（血-HCG）
      - 甲功三项
      - 甲功五项
      - 风湿四项
      - 孕酮测定
      - 免疫球蛋白四项
      - 唐氏综合症Ⅱ期3联
      - 凝血二项 
  dental:
    0:
      - 不限 
      - 全瓷牙
      - 镍铬烤瓷牙
      - 钴铬合金烤瓷牙
      - 钯银合金烤瓷牙
      - 钯金合金烤瓷牙
      - 钛合金烤瓷牙
      - E.MAX全瓷牙
      - 美国"雷诺皓瓷牙"瑞典Procera皓瓷牙
      - 德国泽康皓瓷牙
    49:
      - 不限
      - 乳牙拔除术
      - 前门牙拔除术
      - 双尖牙拔除术
      - 后磨牙拔除术
      - 智齿/残冠拔除
      - 阻生/复杂牙拔除
      - 根尖切除术
    32:
      - 不限
      - 乳牙拔除
      - 前牙拔除
      - 后牙拔除
    0:
      - 不限
      - 正畸保持器
      - 间隙保持器 
    36:
      - 不限
      - 银汞合金补牙
      - SHOUFU激光补牙
      - Ivocar光固化补牙
      - DENSPLY激光补牙
      - Denfil
      - 光固化补牙
      - Coltene光固化补牙
      - 3M
      - 光固化补牙
      - NP钢桩核
      - 钛合金桩核
      - 纯钛桩核（99%）
      - 黄金桩核（86.5%）
      - 全瓷桩核（瑞士康特）
      - 泽康全瓷桩核（德国）
    35:
      - 不限
      - 根管治疗价格（前牙）
      - 根管治疗价格（后牙）
      - 根管再治疗价格（前牙）
      - 根管再治疗价格（后牙）
    33:
      - 不限
      - 进口胶牙
      - 日本塑钢树脂牙
      - 美国生物合金托
      - 纯钛托
    43:
      - 不限
      - 活动矫正器
      - Frankel功能矫正器
      - edgewise方丝弓
      - Andrews直丝弓
      - Begg矫正器
      - 口外支抗矫治器
      - 天使隐形矫正
      - 舌侧隐形矫正
    0:
      - 不限
      - 栓道式精密附件
      - 按扣式精密附件
      - 插销式精密附件
      - 磁吸式精密附件
      - 键槽缓压式精密附件
      - 套筒式精密附件
    0:
      - 不限
      - 全瓷牙价格
      - 镍铬烤瓷牙
      - 钴铬合金烤瓷牙
      - 钯银合金烤瓷牙
      - 钯金合金烤瓷牙
      - 钛合金烤瓷牙
      - E.MAX全瓷牙
      - 美国"雷诺皓瓷牙”
      - 瑞典Procera皓瓷牙
      - 德国泽康皓瓷牙
    48:
      - 不限
      - 碧蓝麻醉注射
      - 无痛麻醉机
    44:
      - 不限
      - 碧蓝麻醉注射
      - 无痛麻醉机
    46:
      - 不限
      - 口腔溃疡治疗
      - 粘膜封闭治疗
      - 口腔取模设计
      - 手术矫正
      - 口腔异物取出
      - 牙周病系统治疗
      - 牙饰粘结
      - 活动义齿修理
      - 内脱色法
      - 粘液囊肿摘除术
      - 骨隆突修整术
      - 牙槽突修整术
      - 系带矫正术
      - 牙齿导萌术
      - 脓肿口内切开引流术
      - 牙槽骨骨折固定术
      - 清创缝合术
      - 颞下颌关节复位术
      - 颞下颌关节封闭术
      - 鼾症矫正器
      - 三叉神经痛封闭
      - 根面平整术
      - 松牙固定术
      - 牙龈成形术
      - 翻瓣术
      - 盲袋切除术
      - 根分叉搔刮手术
      - 牙冠延长术
      - 截根术
      - 分根术
      - 牙半切除术
      - 龈颊沟加深术
      - 上颌窦底提升术
      - 植骨术
      - 种植牙手术
      - 牙移植术
      - 倍骼生植骨术
      - 调合术
      - 拆线
    42:
      - 不限
      - 水门丁粘结
      - POLY-F粘结
      - FUJI1粘结
      - 3M玻璃离子粘结
      - 3M激光树脂粘结
      - 镍铬合金嵌体
      - 钛合金嵌体
      - 钴铬合金嵌体
      - 纯钛嵌体（99%）
      - 黄金嵌体（56%）
      - 黄金嵌体75%
      - 黄金嵌体86.5%
      - 纯钛冠（99%以上）
      - 钴铬合金冠
      - 白金嵌体（97%）
      - IVOCAR全瓷嵌体
      - PROCLAR全瓷嵌体
      - 泽康全瓷嵌体
    34:
      - 不限
      - 胶托全口义齿
      - 钢托全口义齿
      - 纯钛托全口义齿
      - 全口软衬垫底
    47:
      - 不限
      - 牙周冲洗上药
      - PIERO牙周上药
    29:
      - 不限
      - 儿童牙齿矫正
      - 成人牙齿矫正
      - 舌侧牙齿矫正
    0:
      - 不限
      - 冷光牙齿美白
      - 药物牙齿美白
    39:
      - 不限
      - 美国Beyound
      - 美Oplense漂白
    45:
      - 不限
      - NP金属钢冠
      - 黄金冠（86.5%）
      - 钛合金冠
    37:
      - 不限
      - 胶托（小/大）
      - 隐形托（小/大）
      - 钢托（小/大）
      - 钛托（99%）（小/大）
      - 黄金托（小/大）
    41:
      - 不限
      - 临时树脂牙
      - 拆除修复牙冠
      - 拆除金属材料
    0:
      - 不限
      - 种植牙(Dentium系统)
      - 种植牙(德国Bego系统)
      - 种植牙(Osstem，SS系统)
      - 种植牙(Ankylos系统)
      - 种植牙(ITI系统)
      - 种植牙(NOBEL系统)
    40:
      - 不限
      - 国产种植体
      - 韩国种植体
      - ITI种植体
      - Brandmark种植体
    50:
      - 不限
      - X光牙片
      - 全景X光片
      - 咬合X片
      - 头颅侧位片
  doctor:
    0:
      - 不限
      - 主任医师
      - 主任技师
      - 主任检验师
      - 主治医师
      - 主管技师
      - 住院医师
      - 副主任医师
      - 副主任技师
      - 副主任检验师
      - 副主任药师
      - 医师
      - 药师
      - 讲师
      - 高级按摩师
development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults